# Generated by Django 4.2 on 2023-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=100)),
                ("author", models.TextField(max_length=100)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("afterword", models.TextField(blank=True, null=True)),
                ("publisher", models.TextField(blank=True, max_length=100, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("language", models.TextField(max_length=30)),
                ("edition", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
