# Generated by Django 4.2 on 2023-05-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
