# Generated by Django 4.2 on 2023-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_afterword_alter_book_pages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="edition",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
