# Generated by Django 4.2 on 2023-05-05 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="retuned_at",
            new_name="returned_at",
        ),
    ]
