# Generated by Django 4.2 on 2023-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_rename_retuned_at_loan_returned_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="returned_at",
            field=models.DateTimeField(null=True),
        ),
    ]
