# Generated by Django 4.2 on 2023-05-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_date", models.DateTimeField()),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("unblock user", "Unblock User"),
                            ("check returned", "Check Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "loan",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="loans.loan",
                    ),
                ),
            ],
        ),
    ]
